apiVersion: v1
kind: Service
metadata:
  name: banco-mysql-service
  namespace: default
spec:
  selector:
    app: banco-mysql
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: banco-mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    #nodePort: 30007

---

apiVersion: v1
kind: Service
metadata:
  name: app-php-service
  namespace: default
spec:
  selector:
    app: app-php
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: app-php-service
    protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30008